/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {MushroomInfo} from "./Mushroom.tsx";
import {Euler, Vector3} from "three";
import {cloneAndScaleVector} from "../../utils.ts";
import {useControls} from "leva";

interface MushLampGLTFResult extends GLTF  {
    nodes: {
        Foot: THREE.Mesh
        Hat: THREE.Mesh
        Bulbs: THREE.Mesh
        ['off-material-export']: THREE.Mesh // Not needed
    }
    materials: {
        ['Material.003']: THREE.MeshStandardMaterial
        ['Material.001']: THREE.MeshStandardMaterial
        ['material-lamp-on']: THREE.MeshStandardMaterial
        ['material-lamp-off']: THREE.MeshStandardMaterial
    }
}

const MUSH_INFO: MushroomInfo = {
    type: "MushLamp",
    model: "/assets/models/mush-lamp.glb",
    defaultScaleFactor: 0.05,
}

export function MushLamp({
    scaleFactor = 1,
    hatPositionY = 2.716,
    bulbsPositionY = 3.68,
    bulbsRotation = [0.025, 0.712, -0.984],
    bulbsScale = [-0.608, -0.307, -0.481],
    ...props
}) {
    const { nodes, materials } = useGLTF(MUSH_INFO.model) as unknown as MushLampGLTFResult;

    const [lightOn, setLight] = useState(true);
    const {
        lightIntensity
    } = useControls({
        lightIntensity: {
            value: 0.6,
            min: 0,
            max: 20,
            step: 0.1,
        },
    });

    const switchLight = () => {
        setLight(!lightOn);
    }

    const finalScale = MUSH_INFO.defaultScaleFactor * scaleFactor;
    const finalBulbScale = cloneAndScaleVector(new Vector3(...bulbsScale), finalScale);

    return (
        <group {...props} dispose={null}
            onClick={switchLight}
        >

            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Foot.geometry}
                material={materials['Material.003']}
                position={[0, 0, 0]}
                scale={finalScale}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Hat.geometry}
                material={materials['Material.001']}
                position={[0, hatPositionY * finalScale, 0]}
                scale={finalScale}
            >
                <meshPhongMaterial
                    flatShading={true}
                    color={"#400e6b"}
                />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Bulbs.geometry}
                position={[0, bulbsPositionY * finalScale, 0]}
                rotation={new Euler(...bulbsRotation)}
                scale={finalBulbScale}
            >
                <meshPhongMaterial
                    flatShading={true}
                    color={lightOn ? "#f6e495" : "#000000"}
                    emissive={lightOn ? "#f3e6ac" : "#000000"}
                    emissiveIntensity={1}
                    transparent
                    opacity={0.85}
                />

            </mesh>
            <group position={[0, 4.7* finalScale, 0]}>
                {lightOn ? (
                    <>
                    <pointLight
                        castShadow
                        intensity={lightIntensity}
                        color={"#b486e1"}
                        distance={0} />
                    <mesh >
                        <sphereGeometry args={[0.2, 16, 16]} />
                        <meshBasicMaterial color={"#d3b2f1"} transparent opacity={0.009} />
                    </mesh>
                    </>
                    ) : null
                }
            </group>
        </group>
    )
}

useGLTF.preload('/mush-lamp.glb')
