/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, type JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import { type GLTF } from 'three-stdlib';
import {Vector3} from "three";
import {generatePointsInRing} from "./utils.ts";
import {RandomAMuscaria} from "./mushroom/AMuscaria.tsx";

type GLTFResult = GLTF & {
    nodes: {
        tree01: THREE.Mesh
    }
    materials: {
        Mat: THREE.MeshStandardMaterial
    }
}

type TreeProps = JSX.IntrinsicElements['group'] & {
    scale: [x: number, y: number, z: number];
}

const DEFAULT_SCALE_FACTOR = 0.001;

export function Tree({
    scale = [1, 1, 1],
    ...props
    }: TreeProps) {
    const { nodes, materials } = useGLTF('/assets/models/Tree.glb') as GLTFResult
    const finalScale = new Vector3(scale[0] * DEFAULT_SCALE_FACTOR, scale[1] * DEFAULT_SCALE_FACTOR, scale[2] * DEFAULT_SCALE_FACTOR);
    return (
        <group {...props} scale={finalScale} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.tree01.geometry} material={materials.Mat} />
        </group>
    )
}

type TreeFieldProps = {
    center: Vector3,
    innerRadius: number,
    outerRadius: number,
    count: number,
}

export function TreeField({
    center = new Vector3(0, 0, 0),
    innerRadius = 0,
    outerRadius = 1,
    count = 1,
}: TreeFieldProps) {

    const positions = generatePointsInRing(center, innerRadius, outerRadius, count);
    const trees = Array.from({length: count}, (_, i) => {
        return <Tree scale={[1,1,1]} key={i} position={positions[i]}/>
    });
    return <>{trees}</>
}

useGLTF.preload('/assets/models/Tree.glb/Tree.glb')