/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {JSX, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

const glbPath = '/assets/models/mush-musc.glb';

type GLTFResult = GLTF & {
    nodes: {
        Foot: THREE.Mesh
        Collar: THREE.Mesh
        Hat_1: THREE.Mesh
        Hat_2: THREE.Mesh
    }
    materials: {
        ['Material.002']: THREE.MeshStandardMaterial
        ['Material.003']: THREE.MeshStandardMaterial
    }
}

type AMuscariaProps = JSX.IntrinsicElements['group'] & {
    hatScale?: [x: number, y: number, z: number];
    footScale?: [x: number, y: number, z: number];
}

export function AMuscaria({
    hatScale = [1.48, 1, 1.48],
    footScale = [1, 1.031, 1],
    ...props
} : AMuscariaProps) {
    const { nodes, materials } = useGLTF(glbPath) as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Foot.geometry}
                material={materials['Material.002']}
                position={[0, 0, 0]}
                scale={footScale}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Collar.geometry}
                material={nodes.Collar.material}
                position={[0, 3 * footScale[1], 0]}
                rotation={[0, -0.071, 0]}
                scale={1.152}
            />
            <group position={[0, 5 * footScale[1], 0]} scale={hatScale}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Hat_1.geometry}
                    material={materials['Material.003']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Hat_2.geometry}
                    material={nodes.Hat_2.material}
                />
            </group>
        </group>
    )
}

useGLTF.preload(glbPath);