/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {JSX, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import {Vector3} from "three";

type GLTFResult = GLTF & {
    nodes: {
        Chanterelle: THREE.Mesh
    }
    materials: {
        ['Material.001']: THREE.MeshStandardMaterial
    }
}

type ChanterelleProps = JSX.IntrinsicElements['group'] & {
    scaleFactor: number,
}

const glbPath = '/assets/models/mush-chant.glb';

const DEFAULT_SCALE_FACTOR = 0.1;

export function Chanterelle({
    scaleFactor = 1,
    ...props}: ChanterelleProps) {
    const { nodes, materials } = useGLTF(glbPath) as GLTFResult
    const finalScale = new Vector3(1,1,1).multiplyScalar(scaleFactor);
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Chanterelle.geometry}
                material={materials['Material.001']}
                scale={finalScale}
            />
        </group>
    )
}

useGLTF.preload(glbPath)

