/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {JSX, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Foot: THREE.Mesh
        Hat: THREE.Mesh
    }
    materials: {
        ['Material.002']: THREE.MeshStandardMaterial
        ['Material.001']: THREE.MeshStandardMaterial
    }
}

type PorciniProps = JSX.IntrinsicElements['group'] & {
    scaleFactor: number;
};

const glbPath = '/assets/models/mush-porc.glb';

export function Porcini({
    scaleFactor = 1,
    ...props
}) {
    const { nodes, materials } = useGLTF(glbPath) as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Foot.geometry}
                material={materials['Material.002']}
                position={[0, 0, 0]}
                scale={1.094 * scaleFactor}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Hat.geometry}
                material={materials['Material.001']}
                scale={1.094 * scaleFactor}
                position={[0, 1.6 * scaleFactor, 0]}
            />
        </group>
    )
}

useGLTF.preload(glbPath);
